Repository hackclubpoornima/Website, pull requests merged in 2022-10, with the labels that each got.

#6 Changed the content in webpages
  about.html
  faq.html
  gallery.html
  index.html
  static/logos/image-removebg-preview.png
Labels: documentation, hacktoberfest-accepted

#10 'Updated-CSS'
  README.md
  css/normal.css
  img/bg.png
  img/bg1.jpg
  index.html
Labels: enhancement, hacktoberfest-accepted

#15 Responsive!!!!
  about.html
  core.html
  css/main.css
  css/style.css
  faq.html
  gallery.html
  index.html
  js/main.js
  projects.html
Labels: bug, hacktoberfest-accepted

#16 Updated socials
  core.html
Labels: hacktoberfest-accepted
